baseURL = "https://qdrant.tech"
languageCode = "en-us"
title = "Qdrant - Vector Database"
theme = "qdrant-2024"

enableRobotsTXT = true
canonifyURLs = true

keywords = "search engine, vector database, neural network, matching, filter, SaaS, approximate nearest neighbor search, image search, recommender system, vectors, knn algorithm, hnsw, vector search, embeddings, similarity"

disableKinds = ["taxonomy", "term"]

[params]
  description = "Qdrant is an Open-Source Vector Database and Vector Search Engine written in Rust. It provides fast and scalable vector similarity search service with convenient API."
  keywords = ["vector search engine", "neural network", "matching", "SaaS",
    "approximate nearest neighbor search", "image search", "recommender system", "vectors",
    "knn algorithm", "hnsw", "vector search", "embeddings", "similarity", "simaes networks",
    "BERT", "transformer", "word2vec", "fasttext"]

  font = "Anonymous Pro"
  highlight = true
  highlightStyle = "default"
  highlightLanguages = ["python", "rust", "json", "bash", "http"]
  yandexWebmaster = ""

  logo = "/images/logo_with_text.svg"
  logo_width = "192"
  preview_image = "/images/social_preview.png"

  preview_images = [
    "/images/previews/social-preview-A.png",
    "/images/previews/social-preview-B.png",
    "/images/previews/social-preview-C.png",
    "/images/previews/social-preview-D.png",
    "/images/previews/social-preview-E.png",
    "/images/previews/social-preview-F.png",
    "/images/previews/social-preview-G.png",
    "/images/previews/social-preview-H.png",
    "/images/previews/social-preview-I.png",
    "/images/previews/social-preview-J.png",
    "/images/previews/social-preview-K.png",
    "/images/previews/social-preview-L.png",
    "/images/previews/social-preview-M.png",
    "/images/previews/social-preview-N.png",
    "/images/previews/social-preview-O.png",
    "/images/previews/social-preview-P.png"
  ]


  github = "https://github.com/qdrant/qdrant"
  quick_start = "/documentation/quick-start/"
  tutorial = "/articles/neural-search-tutorial/"
  benchmarks = "/benchmarks/"
  demos = "/demo/"
  cloud = "https://qdrant.to/cloud"

  linkedin = "https://qdrant.to/linkedin"
  twitter = "https://qdrant.to/twitter"
  discord = "https://qdrant.to/discord"
  youtube = "https://www.youtube.com/channel/UC6ftm8PwH1RU_LM1jwG0LQA"

  email = "info@qdrant.tech"
  location = "Berlin"

  mailchimp_contact_form = "https://qdrant.to/contact-us"

  mailchimp_subscribe = "https://tech.us1.list-manage.com/subscribe/post?u=69617d79374ac6280dd2230b2&amp;id=acb2b876fc"

  mailchimp_subscribe_id = "b_69617d79374ac6280dd2230b2_acb2b876fc"

  prices_contact_form = "https://share-eu1.hsforms.com/1olUNSzuRRWWXxKJevWfxiA2b46ng"

  gdpr = "We use cookies to learn more about you. At any time you can delete or block cookies through your browser settings."

  githubDocPrefix = "https://github.com/qdrant/landing_page/tree/master/qdrant-landing/content/"
  githubIssueLink = "https://github.com/qdrant/landing_page/issues/new/choose"

  docVersion = "v1.9.x"
  cloudDocVersion = "v0.1.x"

  segmentWriteKey = "noKey"

[params.author]
  name = "Andrey Vasnetsov"
  email = "info@qdrant.tech"

[taxonomies]
    tag = "tags"
    category = "categories"
    example = "examples"

[markup]
  [markup.goldmark.renderer]
    unsafe=true
  [markup.highlight]
    noClasses = false
    codeFences=true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100

# Not rendering the content of the cd following files in production
[[cascade]]
  [cascade._build]
    list = 'never'
    render = 'never'
  [cascade._target]
    environment = '{production}'
    path = '{**.skip,**.skip/*}'

[services]
  [services.googleAnalytics]
    id = 'G-NZYW2651NE'
