baseURL = "https://qdrant.tech"
languageCode = "en-us"
title = "Qdrant - Vector Database"
theme = "qdrant"

googleAnalytics = "G-NZYW2651NE"
enableRobotsTXT = true
canonifyURLs = true

keywords = "search engine, vector database, neural network, matching, filter, SaaS, approximate nearest neighbor search, image search, recommender system, vectors, knn algorithm, hnsw, vector search, embeddings, similarity"


[params]
  author = "Andrey Vasnetsov"
  description = "Qdrant is an Open-Source Vector Database and Vector Search Engine written in Rust. It provides fast and scalable vector similarity search service with convenient API."
  keywords = ["vector search engine", "neural network", "matching", "SaaS",
    "approximate nearest neighbor search", "image search", "recommender system", "vectors",
    "knn algorithm", "hnsw", "vector search", "embeddings", "similarity", "simaes networks",
    "BERT", "transformer", "word2vec", "fasttext"]

  font = "Anonymous Pro"
  highlight = true
  highlightStyle = "default"
  highlightLanguages = ["python", "rust", "json", "bash", "http"]
  yandexWebmaster = ""

  logo = "/images/logo_with_text.svg"
  logo_width = "192"
  preview_image = "/images/social_preview.png"

  preview_images = [
    "/images/previews/social-preview-A.png",
    "/images/previews/social-preview-B.png",
    "/images/previews/social-preview-C.png",
    "/images/previews/social-preview-D.png",
    "/images/previews/social-preview-E.png",
    "/images/previews/social-preview-F.png",
    "/images/previews/social-preview-G.png",
    "/images/previews/social-preview-H.png",
    "/images/previews/social-preview-I.png",
    "/images/previews/social-preview-J.png",
    "/images/previews/social-preview-K.png",
    "/images/previews/social-preview-L.png",
    "/images/previews/social-preview-M.png",
    "/images/previews/social-preview-N.png",
    "/images/previews/social-preview-O.png",
    "/images/previews/social-preview-P.png"
  ]


  github = "https://github.com/qdrant/qdrant"
  quick_start = "/documentation/quick-start/"
  tutorial = "/articles/neural-search-tutorial/"
  benchmarks = "/benchmarks/"
  demos = "/demo"
  cloud = "https://qdrant.to/cloud"

  linkedin = "https://qdrant.to/linkedin"
  twitter = "https://qdrant.to/twitter"
  discord = "https://qdrant.to/discord"
  youtube = "https://www.youtube.com/channel/UC6ftm8PwH1RU_LM1jwG0LQA"

  email = "info@qdrant.tech"
  location = "Berlin"

  mailchimp_contact_form = "https://qdrant.to/contact-us"

  mailchimp_subscribe = "https://tech.us1.list-manage.com/subscribe/post?u=69617d79374ac6280dd2230b2&amp;id=acb2b876fc"

  mailchimp_subscribe_id = "b_69617d79374ac6280dd2230b2_acb2b876fc"

  gdpr = "We use cookies to learn more about you. At any time you can delete or block cookies through your browser settings."

  githubDocPrefix = "https://github.com/qdrant/landing_page/tree/master/qdrant-landing/content/"

  docVersion = "v1.4.x"
  cloudDocVersion = "v0.1.x"

  googleTagManager = "GTM-KRLCXD5"

[taxonomies]
    tag = "tags"
    category = "categories"
    example = "examples"

[menu]

[[menu.main]]
  identifier = "product"
  name = "Product"
  weight = 1
  [menu.main.params]
      in_header = true
      in_footer = true

  [[menu.main]]
    identifier = "use-case"
    name = "Use cases"
    weight = 1
    parent = "product"
    url = "/use-cases/"

  [[menu.main]]
    identifier = "solutions"
    name = "Solutions"
    weight = 2
    parent = "product"
    url = "/solutions/"


  [[menu.main]]
    identifier = "benchmarks"
    name = "Benchmarks"
    weight = 3
    parent = "product"
    url = "/benchmarks/"

  [[menu.main]]
    identifier = "demo"
    name = "Demos"
    weight = 4
    parent = "product"
    url = "/demo/"

  [[menu.main]]
    identifier = "pricing"
    name = "Pricing"
    weight = 5
    parent = "product"
    url = "/pricing/"

[[menu.main]]
  identifier = "resources"
  name = "Resources"
  weight = 2
  [menu.main.params]
    in_header = true
    in_footer = false

  [[menu.main]]
    identifier = "documentation"
    name = "Documentation"
    parent = "resources"
    weight = 1
    url = "/documentation/"

  [[menu.main]]
    identifier = "case-studies"
    name = "Case Studies"
    weight = 2
    parent = "resources"
    url = "/case-studies/"

  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    weight = 4
    parent = "resources"
    url = "/articles/"

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    weight = 5
    parent = "resources"
    url = "https://blog.qdrant.tech/"
    [menu.main.params]
      external = true

  [[menu.main]]
    identifier = "roadmap"
    name = "Roadmap"
    weight = 6
    parent = "resources"
    url = "https://qdrant.to/roadmap"
    [menu.main.params]
       external = true

  [[menu.main]]
    identifier = "changelog"
    name = "Changelog"
    weight = 7
    parent = "resources"
    url = "https://github.com/qdrant/qdrant/releases"
    [menu.main.params]
        external = true

[[menu.main]]
  identifier = "community"
  name = "Community"
  weight = 4
  [menu.main.params]
    in_header = true
    in_footer = true

  [[menu.main]]
    identifier = "github"
    name = "Github"
    weight = 1
    parent = "community"
    url = "https://github.com/qdrant/qdrant"
    pre = "<i class='fab fa-github'></i>"
    [menu.main.params]
        external = true

  [[menu.main]]
    identifier = "discord"
    name = "Discord"
    weight = 2
    parent = "community"
    url = "https://qdrant.to/discord"
    pre = "<i class='fab fa-discord'></i>"
    [menu.main.params]
      external = true

  [[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    weight = 3
    parent = "community"
    url = "https://qdrant.to/twitter"
    pre = "<i class='fab fa-twitter'></i>"
    [menu.main.params]
      external = true

  [[menu.main]]
    identifier = "newsletter"
    name = "Newsletter"
    weight = 4
    parent = "community"
    url = "/subscribe/"
    pre = "<i class='fas fa-mail-bulk'></i>"

  [[menu.main]]
    identifier = "contact"
    name = "Contact us"
    weight = 5
    parent = "community"
    url = "https://qdrant.to/contact-us"
    pre = "<i class='fas fa-envelope'></i>"
    [menu.main.params]
      external = true

[[menu.main]]
  identifier = "company"
  name = "Company"
  weight = 4
  [menu.main.params]
    in_header = false
    in_footer = true

  [[menu.main]]
    identifier = "jobs"
    name = "Jobs"
    weight = 1
    parent = "company"
    url = "https://qdrant.join.com"

  [[menu.main]]
    identifier = "privacy-policy"
    name = "Privacy Policy"
    weight = 2
    parent = "company"
    url = "/legal/privacy-policy/"

  [[menu.main]]
    identifier = "terms"
    name = "Terms"
    weight = 3
    parent = "company"
    url = "/legal/terms_and_conditions/"

  [[menu.main]]
    identifier = "impressum"
    name = "Impressum"
    weight = 4
    parent = "company"
    url = "/legal/impressum/"

  [[menu.main]]
    identifier = "credits"
    name = "Credits"
    weight = 5
    parent = "company"
    url = "/legal/credits/"

[markup]
  [markup.goldmark.renderer]
    unsafe=true
  [markup.highlight]
    style='friendly'
   codeFences=true
