[package]
name = "snippets-amalgamation"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
qdrant-client = { git = "https://github.com/qdrant/rust-client", branch = "master" }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
uuid = { version = "1.18.1", features = ["v4"] }
