name = "Qdrant"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://qdrant.tech/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Andrei Vasnetsov"
  homepage = "https://vasnetsov.com/"
